name: The Perth Pop Up Wedding Company
favicon: null
layout_spectrum: 0.025954172713682055
typography_spectrum: 0.1726640781853348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8991311118006706
  lightness: 0.7436422612518072
  saturation: 0.7311458899639547
  rhythmicContrast: 0.33105706865899265
purpose: []
